import Head from 'next/head'

import fs from 'fs'
import path from 'path'

import matter from 'gray-matter'

import BlogsContainer from '../components/BlogsContainer/BlogsContainer'

export default function Home({posts}) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      

      <BlogsContainer posts={posts} />
    </>
  )
}

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('posts'))

  const posts = files.map(file => {
    const markdownWithMeta = fs.readFileSync(path.join('posts', file), 'utf8')
    const { data: frontMatter } = matter(markdownWithMeta)

    return {
      frontMatter,
      slug: file.split('.')[0]
    }
  })

  return {
    props: {
      posts
    }
  }
}
